all: main
main: main.cpp NCursesGameScreenBorder.hpp Grid.hpp Grid.cpp NCursesGameScreenBorder.cpp GamePlay.cpp MenuList.cpp MenuList.hpp GamePlay.hpp Menu.hpp Menu.cpp NCursesFunctions.cpp NCursesFunctions.hpp
	g++ main.cpp Grid.cpp NCursesGameScreenBorder.cpp NCursesFunctions.cpp GamePlay.cpp Menu.cpp MenuList.cpp -o main -lncurses
	

.PHONY: all clean